version: '3.8'

services:
  web:
    build: .
    command: python /noteadder/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/noteadder
    ports:
      - 8000:8000
      - 35729:35729
    depends_on:
      - selenium
      - db
  
  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
  
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: