version: '3.8'

services:
  web:
    build: .
    command: python /noteadder/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/noteadder
    ports:
      - 8000:8000
      - 35729:35729
    depends_on:
      - selenium
      - db
    environment: 
      - "DJANGO_SECRET_KEY=-60y7u=x$$87)0vntl=eeo+#)0i9sktlsbjf)l=lz@bu$$=sy=bw"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  
  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
  
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: